package frontier

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
)

func LoadContract(path string) (Contract, []byte, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return Contract{}, nil, err
	}
	var contract Contract
	decoder := json.NewDecoder(strings.NewReader(string(raw)))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&contract); err != nil {
		return Contract{}, nil, err
	}
	if err := ValidateContract(contract); err != nil {
		return Contract{}, nil, err
	}
	return contract, raw, nil
}

func ValidateContract(contract Contract) error {
	if contract.Schema != ProtocolSchema+"/denominator/v1" {
		return errors.New("INVALID_CONTRACT_SCHEMA")
	}
	if contract.DenominatorID == "" || contract.FixedDenominator != 12 || contract.MetaActivityCount != 12 || len(contract.Cells) != 12 {
		return errors.New("INVALID_FIXED_DENOMINATOR")
	}
	if len(contract.StatePrecedence) != 3 || contract.StatePrecedence[0] != StateRefuted || contract.StatePrecedence[1] != StateUnknown || contract.StatePrecedence[2] != StateClosed {
		return errors.New("INVALID_STATE_PRECEDENCE")
	}
	seenClaims := map[string]bool{}
	seenOperations := map[string]bool{}
	for index, cell := range contract.Cells {
		if cell.Ordinal != index+1 || cell.ClaimID == "" || cell.OperationID == "" || cell.Stage == "" || cell.Step == "" || !validProofChoice(ProofChoice(cell.ProofChoice)) {
			return fmt.Errorf("INVALID_CONTRACT_CELL_%d", index+1)
		}
		if seenClaims[cell.ClaimID] || seenOperations[cell.OperationID] {
			return errors.New("DUPLICATE_CONTRACT_CELL")
		}
		seenClaims[cell.ClaimID] = true
		seenOperations[cell.OperationID] = true
	}
	if len(contract.ForbiddenRanking) == 0 {
		return errors.New("MISSING_FORBIDDEN_RANKING")
	}
	return nil
}

func CompileSource(sourcePath string, source []byte, contract Contract, contractDigest string) (SemanticIR, error) {
	if err := ValidateContract(contract); err != nil {
		return SemanticIR{}, err
	}
	lines := strings.Split(string(source), "\n")
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != `@gooo schema="gooo/improvement-frontier/v1"` {
		return SemanticIR{}, errors.New("GOOO_SOURCE_SCHEMA_HEADER_MISSING")
	}
	activities := make([]SourceActivity, 0, len(contract.Cells))
	for lineNumber, rawLine := range lines {
		line := strings.TrimSpace(rawLine)
		if !strings.HasPrefix(line, "activity ") {
			continue
		}
		attrs, err := parseAttributes(strings.TrimPrefix(line, "activity "))
		if err != nil {
			return SemanticIR{}, fmt.Errorf("source line %d: %w", lineNumber+1, err)
		}
		activity := SourceActivity{
			ClaimID: attrs["claim_id"], OperationID: attrs["operation_id"], Stage: attrs["stage"],
			Step: attrs["step"], ProofChoice: attrs["proof_choice"], SourceLine: lineNumber + 1,
		}
		if activity.ClaimID == "" || activity.OperationID == "" || activity.Stage == "" || activity.Step == "" || !validProofChoice(ProofChoice(activity.ProofChoice)) {
			return SemanticIR{}, fmt.Errorf("source line %d: INCOMPLETE_ACTIVITY_METADATA", lineNumber+1)
		}
		activities = append(activities, activity)
	}
	if len(activities) != contract.MetaActivityCount {
		return SemanticIR{}, errors.New("GOOO_SOURCE_DENOMINATOR_CARDINALITY_MISMATCH")
	}
	for index, cell := range contract.Cells {
		activity := activities[index]
		if activity.ClaimID != cell.ClaimID || activity.OperationID != cell.OperationID || activity.Stage != cell.Stage || activity.Step != cell.Step || activity.ProofChoice != cell.ProofChoice {
			return SemanticIR{}, fmt.Errorf("GOOO_ACTIVITY_BINDING_MISMATCH_%d", cell.Ordinal)
		}
	}
	return SemanticIR{
		Schema: IRSchema, SourcePath: sourcePath, SourceDigest: DigestBytes(source), ContractDigest: contractDigest,
		MetaActivityCount: len(activities), Activities: activities,
	}, nil
}

func SemanticIRBytes(ir SemanticIR) ([]byte, error) {
	raw, err := json.MarshalIndent(ir, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(raw, '\n'), nil
}

func GenerateGo(ir SemanticIR, semanticDigest string) []byte {
	var builder strings.Builder
	builder.WriteString("// Code generated by gooo. DO NOT EDIT.\n\n")
	builder.WriteString("package generated\n\n")
	builder.WriteString("const ProtocolSchema = \"gooo/improvement-frontier/protocol/v1\"\n")
	fmt.Fprintf(&builder, "const SourcePath = %q\n", ir.SourcePath)
	fmt.Fprintf(&builder, "const SourceDigest = %q\n", ir.SourceDigest)
	fmt.Fprintf(&builder, "const SemanticIRPath = %q\n", "internal/generated/semantic-ir.json")
	fmt.Fprintf(&builder, "const SemanticIRDigest = %q\n", semanticDigest)
	fmt.Fprintf(&builder, "const ContractPath = %q\n", "contracts/improvement-frontier-denominator-v1.json")
	fmt.Fprintf(&builder, "const ContractDigest = %q\n", ir.ContractDigest)
	fmt.Fprintf(&builder, "const MetaActivityCount = %d\n\n", ir.MetaActivityCount)
	builder.WriteString("type Activity struct {\n\tClaimID     string\n\tOperationID string\n\tStage       string\n\tStep        string\n\tProofChoice string\n}\n\n")
	builder.WriteString("var Activities = []Activity{\n")
	for _, activity := range ir.Activities {
		fmt.Fprintf(&builder, "\t{ClaimID: %q, OperationID: %q, Stage: %q, Step: %q, ProofChoice: %q},\n", activity.ClaimID, activity.OperationID, activity.Stage, activity.Step, activity.ProofChoice)
	}
	builder.WriteString("}\n")
	return []byte(builder.String())
}

func parseAttributes(input string) (map[string]string, error) {
	attrs := map[string]string{}
	for position := 0; position < len(input); {
		for position < len(input) && input[position] == ' ' {
			position++
		}
		if position == len(input) {
			break
		}
		keyStart := position
		for position < len(input) && input[position] != '=' && input[position] != ' ' {
			position++
		}
		if keyStart == position || position >= len(input) || input[position] != '=' {
			return nil, errors.New("INVALID_ATTRIBUTE")
		}
		key := input[keyStart:position]
		if _, exists := attrs[key]; exists {
			return nil, errors.New("DUPLICATE_ATTRIBUTE")
		}
		position++
		if position >= len(input) || input[position] != '"' {
			return nil, errors.New("ATTRIBUTES_MUST_BE_QUOTED")
		}
		valueStart := position
		position++
		for position < len(input) {
			if input[position] == '"' && input[position-1] != '\\' {
				position++
				break
			}
			position++
		}
		if position > len(input) || position == 0 || input[position-1] != '"' {
			return nil, errors.New("UNTERMINATED_ATTRIBUTE")
		}
		value, err := strconv.Unquote(input[valueStart:position])
		if err != nil {
			return nil, err
		}
		attrs[key] = value
	}
	return attrs, nil
}

func validProofChoice(choice ProofChoice) bool {
	return choice == ProofFoundation || choice == ProofCoherence || choice == ProofRegression
}
